### ISSUE TITLE
New users never activated when activation field disabled

### ISSUE THREAD

**Issue by devinbethel** [voidet/sign_me_up#1]
When activation is disabled by setting activation field config setting to false, the database column 'active' is never set to 1 when a new user registers. (Easily worked around by setting the default column value to 1 ;)

**Comment by voidet** [comment]
Featured added after much debate :) I'd rather provide more features. Also while I was at it I added in the ability to load config from the config file if no inline config is specified. Thanks for your feature suggestion.
