### ISSUE TITLE
Unknown email configuration &quot;signMeUp&quot;.

### ISSUE THREAD

**Issue by darksnow** [voidet/sign_me_up#11]
After following the instructions to set this plugin up on Cake 2.0, any time the plugin is used I get this error.

I've tracked it down to line 41 of SignMeUpComponent.php which creates an instance of CakeEmail. It's looking for the signMeUp email settings in the EmailConfig object in email.php

There was no mention of editing that file in the instructions on jotlab so I'm a little unsure what is required in that file. The instructions do mention overriding email settings in the sign me up config file. I'm a little unclear what, if anything, is needed in that file.

Is anyone else getting this error and how should I work around it?

Cheers.

**Comment by voidet** [comment]
Thanks for this.
I will patch this issue up but for the time being you should be able to use:

```
public $signMeUp = array(
    'transport' => 'Mail',
    'from' => 'me@me.com',
    //'charset' => 'utf-8',
    //'headerCharset' => 'utf-8',
);
```

in your app/Config/email.php file

**Comment by ipansensoy** [comment]
hi there im getting this error

Could not send email.
Error: An Internal Error Has Occurred.

Stack Trace
CORE\Cake\Network\Email\CakeEmail.php line 972 → MailTransport->send(CakeEmail)
APP\Plugin\sign_me_up\Controller\Component\SignMeUpComponent.php line 277 → CakeEmail->send()
APP\Plugin\sign_me_up\Controller\Component\SignMeUpComponent.php line 260 → SignMeUpComponent->__sendForgottenPassword(array)
APP\Plugin\sign_me_up\Controller\Component\SignMeUpComponent.php line 216 → SignMeUpComponent->__requestNewPassword(array, string)
APP\Controller\UsersController.php line 111 → SignMeUpComponent->forgottenPassword()
[internal function] → UsersController->forgotten_password()
CORE\Cake\Controller\Controller.php line 485 → ReflectionMethod->invokeArgs(UsersController, array)
CORE\Cake\Routing\Dispatcher.php line 103 → Controller->invokeAction(CakeRequest)
CORE\Cake\Routing\Dispatcher.php line 85 → Dispatcher->_invoke(UsersController, CakeRequest, CakeResponse)
APP\webroot\index.php line 92 → Dispatcher->dispatch(CakeRequest, CakeResponse)
