### ISSUE TITLE
Not working in cakephp 2.2x

### ISSUE THREAD

**Issue by joserafael** [voidet/sign_me_up#14]
Hello voidet. I use this plugin from cakephp 1.3.7. Really wonderful. Only work to 2.1.x. Do you think to update to cakephp 2.2.x? Thank you.

**Comment by cosmin-novac** [comment]
That would be really great of you voidet!

**Comment by abshkd** [comment]
+1, i have to 2.2+ for a bug that is their in earlier versions of Cake, but registration is currently broken.
