### ISSUE TITLE
Documentation incomplete for cakephp 2.0

### ISSUE THREAD

**Issue by abshkd** [voidet/sign_me_up#4]
Using cakephp 2.0
When doing exactly as per the docs and visiting any of the signmeup urls gives the following error.

Error: The application is trying to load a file from the SignMeUp plugin

Error: Make sure your plugin SignMeUp is in the app/Plugin directory and was loaded
<?php
CakePlugin::load('SignMeUp');

I proceeded to add it in User Controller where I want to use the SignMeUp methods. However this throws a new error

Error: SignMeUp.SignMeUpComponent could not be found.

Error: Create the class SignMeUpComponent below in file: /home/freeeasy/beta.3ezy.net/app/Plugin/sign_me_up/Controller/Component/SignMeUpComponent.php

<?php
class SignMeUpComponent extends Component {

}

I believe the git url in the docs may be wrong but I am not sure.

**Comment by voidet** [comment]
Updated docs to load the plugin thank you. Not sure why component isn't found, will look into that.

**Comment by er777** [comment]
I am getting the exact same error. Followed instructions to the "T". Did you look into it?
