### ISSUE TITLE
Fatal error: Call to a member function allow() on a non-object 

### ISSUE THREAD

**Issue by abshkd** [voidet/sign_me_up#5]
When I use the example. I also get this error when accessing any page under the controller.

There is no other trace or debug I can provide as the fatal error stops execution. I have included the user controller code below for reference.

```
class UsersController extends AppController {
 public $components = array('SignMeUp.SignMeUp');




 public function register() {
  $this->SignMeUp->register();
  }

public function activate() {
  $this->SignMeUp->activate();
}

public function forgotten_password() {
 $this->SignMeUp->forgottenPassword();
}


 public function beforeFilter() {
    $this->Auth->allow(array('login', 'forgotten_password', 'register', 'activate'));
    parent::beforeFilter();
 }
}
```

I am assuming that i do not need to declare Auth in my app controller do i? I assumed Sigmeup was doing that. If not then what is the correct way?

**Comment by abshkd** [comment]
sorry not relevant. I mixed up the auth and signmeup in this comment.

**Comment by voidet** [comment]
Is this okay to close as a non-issue?

**Comment by abshkd** [comment]
Yes I think its a non issue.
