### ISSUE TITLE
Forgotten Password Broken? 

### ISSUE THREAD

**Issue by jamiechong** [voidet/sign_me_up#6]
It seems like the forgotten_password functionality is broken in your 2.0 branch. I'm using CakePHP 2.1. It occurs when the user clicks the link in the email to have the password reset. Since you're using named paramaters, I believe line 214 in SignMeUpComponent should be 

```
    if (!empty($this->controller->params['named'][$password_reset_field])) {
```

and line 224 should be: 

```
        'conditions' => array($password_reset_field => $this->controller->params['named'][$password_reset_field]),
```

**Comment by voidet** [comment]
Hi Jamie,

I am not too sure this is correct as the routes should capture this into the root level params array.
Can you please show me the routes you are using? If you are right this extends beyond the password reset.

Thanks

**Comment by jamiechong** [comment]
I literally took the routes you posted in your readme:

Router::connect('/register', array('controller' => 'Users', 'action' =>
'register'));
Router::connect('/activate', array('controller' => 'Users', 'action' =>
'activate'));
Router::connect('/activate/:activation_code', array('controller' =>
'Users', 'action' => 'activate'), array('pass' => 'activation_code'));
Router::connect('/forgotten_password/:password_reset', array('controller'
=> 'Users', 'action' => 'forgotten_password'), array('pass' =>
'password_reset_code'));
Router::connect('/login', array('controller' => 'Users', 'action' =>
'login'));
Router::connect('/logout', array('controller' => 'Users', 'action' =>
'logout'));

Keep in mind I'm using CakePHP 2.1, I kind of remember seeing somewhere
that the Request object has changed a bit. In the controller it's better to
use $this->request. I didn't dig too deeply, so hopefully I'm mistaken :)

On Wed, Apr 25, 2012 at 4:38 PM, Richard S <
reply@reply.github.com

**Comment by voidet** [comment]
Thanks for that.
I will test in 2.1 and get back to this issue.

**Comment by lukasberns** [comment]
Same issue in `activate()` (I'm using CakePHP 2.1, too)

Around line 165 in `SignMeUpComponent.php` should be changed to

```
//Test for an activation code in the parameters
if (!empty($this->controller->params['named'][$activation_field])) {
    $activation_code = $this->controller->params['named'][$activation_field];
```

Right now the page will always display the "Please paste your activation code below" input box

**Comment by voidet** [comment]
Thanks Lukasberns,
This issue should now be resolved without using the named routes in the params array.
Cake 2.1 params are now stored under the request object. Updated SignMeUp to meet this.

**Comment by lukasberns** [comment]
Hmm your commit doesn't work for me.
It works if I replace

```
$this->controller->request->params['...']
```

with

```
$this->controller->request->named['...']
```

That's what the docs say, too: http://book.cakephp.org/2.0/en/controllers/request-response.html#accessing-request-parameters

**Comment by voidet** [comment]
Hmm. Please paste your routes here. My named params is empty. And all urls are working as expected.

**Comment by lukasberns** [comment]
Aha! I didn’t configure the routes…
I’m new to CakePHP and didn't know that connecting a route moves a param from `named` to `params`. Working now, thanks :)

**Comment by voidet** [comment]
That's exactly what I thought was happening.
I specifically don't want to use named parameters here, firstly because it looks unprofessional in signups, but secondly because it makes your DB field names visible.

**Comment by ipansensoy** [comment]
having the same issue here email activate link will only show activation field
